#!/usr/bin/env php
<?php

error_reporting(\E_ALL);

set_error_handler(function ($severity, $message, $file, $line) {
    if (error_reporting() & $severity) {
        throw new \ErrorException($message, 0, $severity, $file, $line);
    }
});

require __DIR__ . '/paths.php';
require __DIR__ . '/vendor/autoload.php';

(new Application\Console\ConsoleApplication())->run();
